_target_: lsystem.config.LSystemConfig
name: "Koch Snowflake L-System"

grammar:
  _target_: lsystem.model.grammar.Grammar.from_dict
  nonterminals: [F]
  terminals: [+, -]
  rules: [
    [F, F+F--F+F]
  ]
  axiom: F--F--F

renderer_config:
  line_segment_length: 500
  line_segment_length_reduction: 0.33333
  angle_offset: 60

  instruction_mapping:
    _target_: lsystem.mapping.InstructionMapping.from_dict
    map: {
      'F': FORWARD,
      '+': RIGHT,
      '-': LEFT,
    }
    
  starting_state:
    _target_: lsystem.renderer.RendererState
    x: -250
    y: -150
    angle: 0
