_target_: lsystem.config.LSystemConfig
name: "Sierpinsky Triangle L-System"

grammar:
  _target_: lsystem.model.grammar.Grammar.from_dict
  nonterminals: [L, R]
  terminals: [+, -]
  rules: [
    [L, R+L+R],
    [R, L-R-L],
  ]
  axiom: R
  
renderer_config:
  line_segment_length: -400
  line_segment_length_reduction: 0.5
  angle_offset: 60

  instruction_mapping:
    _target_: lsystem.mapping.InstructionMapping.from_dict
    map: {
      'L': FORWARD,
      'R': FORWARD,
      '+': RIGHT,
      '-': LEFT,
    }

  starting_state:
    _target_: lsystem.renderer.RendererState
    x: -200
    y: 0
    angle: 180
