from typing import Tuple

from lsystem.model.word import Word

__all__ = ['LSystemRenderer']


class LSystemState:

    def __init__(self, location: Tuple[int, int], angle: int) -> None:
        self.x = location[0]
        self.y = location[1]
        self.angle = angle


# TODO Map instructions to the symbols of a word generated by lsystem grammar
# TODO Interpret the instructions and use them to draw
# TODO Pushing state of the renderer to the stack

# TODO Shortening of edges with - subsequent steps ?
#                               - branching ?

class LSystemRenderer():

    def __init__(self, starting_state: LSystemState, location_delta: int, angle_delta: int, ) -> None:

        self.current_state = starting_state

        self.location_delta = location_delta
        self.angle_delta = angle_delta

        self.state_stack = []

    def render(self, word: Word):

        for instruction in word:
            pass
